=== realitix/Ingres-Community-Edition/src/common/adf/adn/charactermappingaliases.dtd
<!ELEMENT characterMappingAliases (mapping*)>
<!--
** DTD file for XML formatted alias table for xml.
** Ref: http://www.unicode.org/unicode/reports/tr22 CharacterMapping-3.dtd.
**
-->

<!ELEMENT mapping (display*, alias*, bestFit*)>
<!ATTLIST mapping
    id CDATA #REQUIRED
>

<!ELEMENT display EMPTY>
<!ATTLIST display
    xml:lang CDATA #REQUIRED
    name CDATA #REQUIRED
>

<!ELEMENT alias EMPTY>
<!ATTLIST alias
    name CDATA #REQUIRED
    preferredBy CDATA #IMPLIED
>

<!ELEMENT bestFit EMPTY>
<!ATTLIST bestFit 
    id CDATA #REQUIRED
    matchingA CDATA #REQUIRED
    matchingB CDATA #REQUIRED
>

=== realitix/Ingres-Community-Edition/src/common/adf/adn/charmapalias.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE characterMappingAliases SYSTEM "charactermappingaliases.dtd">
<!-- 
** Copyright (c) 2004 Actian Corporation
**
** =============================================================================
** ICU License - ICU 1.8.1 and later
** COPYRIGHT AND PERMISSION NOTICE
**  
** Copyright (c) 1995-2003 International Business Machines Corporation and others
** All rights reserved.
**  
** Permission is hereby granted, free of charge, to any person obtaining a
** copy of this software and associated documentation files (the
** "Software"), to deal in the Software without restriction, including
** without limitation the rights to use, copy, modify, merge, publish,
** distribute, and/or sell copies of the Software, and to permit persons
** to whom the Software is furnished to do so, provided that the above
** copyright notice(s) and this permission notice appear in all copies of
** the Software and that both the above copyright notice(s) and this
** permission notice appear in supporting documentation.
**  
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
** OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
** MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
** OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
** HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL
** INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING
** FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
** NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
** WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
**  
** Except as contained in this notice, the name of a copyright holder
** shall not be used in advertising or otherwise to promote the sale, use
* or other dealings in this Software without prior written authorization
* of the copyright holder.
** =============================================================================
*/
##
## History:
##      26-Jan-2004 (gupsh01)
##          Created based on UTR22.
##
-->

<!-- Fully algorithmic converters -->
<characterMappingAliases>
<mapping id="UTF-8">
  <alias name="ibm-1208" preferredBy="IBM*"/>
  <alias name="ibm-1209" preferredBy="IBM"/>
  <alias name="ibm-5304" preferredBy="IBM"/>
  <alias name="ibm-5305" preferredBy="IBM"/>
  <alias name="windows-65001" preferredBy="WINDOWS*"/>
  <alias name="cp1208"/>
</mapping>

<!-- Standard iso-8859-1, Does not have Euro update. -->
<mapping id="ca-iso8859-1-latin1-2004">
  <alias name="ibm-819" preferredBy="IBM* JAVA"/>
  <alias name="IBM819" preferredBy="IANA"/>
  <alias name="cp819" preferredBy="IANA JAVA"/>
  <alias name="latin1" preferredBy="IANA JAVA"/>
  <alias name="8859_1" preferredBy="JAVA"/>
  <alias name="csISOLatin1" preferredBy="IANA JAVA"/>
  <alias name="iso-ir-100" preferredBy="IANA JAVA"/>
  <alias name="ISO_8859-1:1987" preferredBy="IANA* JAVA"/>
  <alias name="l1" preferredBy="IANA JAVA"/>
  <alias name="819" preferredBy="JAVA"/>
  <alias name="iso88591" preferredBy="INGRES"/>
  <alias name="C" preferredBy="UNIX"/>
  <alias name="POSIX" preferredBy="UNIX"/>
</mapping>

<!-- LATIN_1" -->
<mapping id="ca-us-ascii-2004">
  <alias name="ASCII" preferredBy="JAVA* IANA WINDOWS"/>
  <alias name="ANSI_X3.4-1968" preferredBy="IANA* WINDOWS"/>
  <alias name="ANSI_X3.4-1986" preferredBy="IANA WINDOWS"/>
  <alias name="ISO_646.irv:1991" preferredBy="IANA WINDOWS"/>
  <alias name="iso_646.irv:1983" preferredBy="JAVA"/>
  <alias name="ISO646-US" preferredBy="JAVA IANA WINDOWS"/>
  <alias name="us" preferredBy="IANA"/>
  <alias name="csASCII" preferredBy="IANA WINDOWS"/>
  <alias name="iso-ir-6" preferredBy="IANA"/>
  <alias name="cp367" preferredBy="IANA WINDOWS"/>
  <alias name="ascii7" preferredBy="JAVA"/>
  <alias name="646" preferredBy="JAVA"/>
  <alias name="windows-20127" preferredBy="WINDOWS*"/>
</mapping>

<!-- Table-based interchange codepages -->

<!-- This is ASCII, with fallbacks -->
<mapping id="ca-ibm367-ascii-2004">
  <alias name="ibm-367" preferredBy="IBM*"/>
  <alias name="IBM367" preferredBy="IANA*"/>
</mapping>

<!-- Central Europe -->
<mapping id="ca-iso8859-2-latin2-2004">
  <alias name="ibm-912" preferredBy="IBM* JAVA"/>
  <alias name="iso-8859-2" preferredBy="MIME* IANA JAVA* WINDOWS"/>
  <alias name="ISO_8859-2:1987" preferredBy="IANA* WINDOWS JAVA"/>
  <alias name="latin2" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="csISOLatin2" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="iso-ir-101" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="l2" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="8859_2" preferredBy="JAVA"/>
  <alias name="cp912" preferredBy="JAVA"/>
  <alias name="912" preferredBy="JAVA"/>
  <alias name="windows-28592" preferredBy="WINDOWS*"/>
  <alias name="iso88592" preferredBy="INGRES"/>
</mapping>

<!-- Cyrillic -->
<mapping id="ca-iso8859-5-cyrillic-2004">
  <alias name="ibm-915" preferredBy="IBM* JAVA"/>
  <alias name="iso-8859-5" preferredBy="MIME* IANA WINDOWS JAVA*"/>
  <alias name="cyrillic" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="csISOLatinCyrillic" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="iso-ir-144" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="ISO_8859-5:1988" preferredBy="IANA* WINDOWS JAVA"/>
  <alias name="8859_5" preferredBy="JAVA"/>
  <alias name="cp915" preferredBy="JAVA"/>
  <alias name="915" preferredBy="JAVA"/>
  <alias name="windows-28595" preferredBy="WINDOWS*"/>
  <alias name="iso88595" preferredBy="INGRES"/>
</mapping>

<!-- Arabic -->
<!-- ISO_8859-6-E and ISO_8859-6-I are similar to this charset, but BiDi is done differently-->
<!-- From a narrow mapping point of view, there is no difference.-->
<!-- -E means explicit. -I means implicit.-->
<!-- -E requires the client to handle the ISO 6429 bidirectional controls-->
<mapping id="ca-iso8859-6-arabic-2004">
  <alias name="ibm-1089" preferredBy="IBM* JAVA"/>
  <alias name="iso-8859-6" preferredBy="MIME* IANA WINDOWS JAVA*"/>
  <alias name="arabic" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="csISOLatinArabic" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="iso-ir-127" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="ISO_8859-6:1987" preferredBy="IANA* WINDOWS JAVA"/>
  <alias name="ECMA-114" preferredBy="IANA JAVA"/>
  <alias name="ASMO-708" preferredBy="IANA JAVA"/>
  <alias name="8859_6" preferredBy="JAVA"/>
  <alias name="cp1089" preferredBy="JAVA"/>
  <alias name="1089" preferredBy="JAVA"/>
  <alias name="windows-28596" preferredBy="WINDOWS*"/>
  <alias name="ISO-8859-6-I" preferredBy="IANA MIME"/>
<!-- IANA considers this alias different and BiDi needs to be applied. -->
  <alias name="ISO-8859-6-E" preferredBy="IANA MIME"/>
<!-- IANA considers this alias different and BiDi needs to be applied. -->
  <alias name="dosasmo" preferredBy="INGRES"/>
</mapping>

<!-- ISO Greek (w/o euro update) -->
<mapping id="ca-iso8859-7-greek-2004">
  <alias name="ibm-813" preferredBy="IBM* JAVA"/>
  <alias name="iso-8859-7" preferredBy="MIME* IANA WINDOWS JAVA*"/>
  <alias name="greek" preferredBy="IANA WINDOWS JAVA INGRES"/>
  <alias name="greek8" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="ELOT_928" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="ECMA-118" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="csISOLatinGreek" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="iso-ir-126" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="ISO_8859-7:1987" preferredBy="IANA* WINDOWS JAVA"/>
  <alias name="8859_7" preferredBy="JAVA"/>
  <alias name="cp813" preferredBy="JAVA"/>
  <alias name="813" preferredBy="JAVA"/>
  <alias name="windows-28597" preferredBy="WINDOWS*"/>
</mapping>

<!-- hebrew -->
<!-- ISO_8859-8-E and ISO_8859-8-I are similar to this charset, but BiDi is done differently -->
<!-- From a narrow mapping point of view, there is no difference. -->
<!-- -E means explicit. -I means implicit. -->
<!-- -E requires the client to handle the ISO 6429 bidirectional controls -->
<mapping id="ca-iso8859-8-hebrew-2004">
  <alias name="ibm-916" preferredBy="IBM* JAVA"/>
  <alias name="iso-8859-8" preferredBy="MIME* IANA WINDOWS JAVA*"/>
  <alias name="hebrew" preferredBy="IANA WINDOWS JAVA INGRES"/>
  <alias name="csISOLatinHebrew" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="iso-ir-138" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="ISO_8859-8:1988" preferredBy="IANA* WINDOWS JAVA"/>
  <alias name="ISO-8859-8-I" preferredBy="IANA MIME"/>
<!-- IANA and Windows considers this alias different and BiDi needs to be applied. -->
  <alias name="ISO-8859-8-E" preferredBy="IANA MIME"/>
<!-- IANA and Windows considers this alias different and BiDi needs to be applied. -->
  <alias name="8859_8" preferredBy="JAVA"/>
  <alias name="cp916" preferredBy="JAVA"/>
  <alias name="916" preferredBy="JAVA"/>
  <alias name="windows-28598" preferredBy="WINDOWS*"/>
</mapping>

<!-- Turkish -->
<mapping id="ca-iso8859-9-turkish-2004">
  <alias name="ibm-920" preferredBy="IBM* JAVA"/>
  <alias name="iso-8859-9" preferredBy="MIME* IANA WINDOWS JAVA*"/>
  <alias name="latin5" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="csISOLatin5" preferredBy="IANA JAVA"/>
  <alias name="iso-ir-148" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="ISO_8859-9:1989" preferredBy="IANA* WINDOWS"/>
  <alias name="l5" preferredBy="IANA WINDOWS JAVA"/>
  <alias name="8859_9" preferredBy="JAVA"/>
  <alias name="cp920" preferredBy="JAVA"/>
  <alias name="920" preferredBy="JAVA"/>
  <alias name="windows-28599" preferredBy="WINDOWS*"/>
  <alias name="ECMA-128"/>
  <alias name="iso88599" preferredBy="INGRES"/>
<!-- IANA doesn't have this alias 6/24/2002 -->
</mapping>

<!-- Latin 9 -->
<mapping id="ca-iso8859-15-latin9-2004">
  <alias name="ibm-923" preferredBy="IBM* JAVA"/>
  <alias name="iso-8859-15" preferredBy="IANA* MIME* WINDOWS JAVA*"/>
  <alias name="Latin-9" preferredBy="IANA WINDOWS"/>
  <alias name="l9" preferredBy="WINDOWS"/>
