=== realitix/Ingres-Community-Edition/src/common/adf/adn/charactermapping.dtd
<!ELEMENT characterMapping (history?, ((validity|stateful_siso), assignments))>

<!ATTLIST characterMapping
    id CDATA #REQUIRED
    version CDATA #REQUIRED
    description CDATA #IMPLIED
    contact CDATA #IMPLIED
    registrationAuthority CDATA #IMPLIED
    registrationName CDATA #IMPLIED
    copyright CDATA #IMPLIED
    bidiOrder (logical|RTL|LTR) "logical"
    combiningOrder (before|after) "after"
    normalization (undetermined|neither|NFC|NFD|NFC_NFD) "undetermined"
>

<!--
    The stateful_siso element is an alternative to one single validity element,
    and contains two validity specifications:
    The single-byte specification followed by the double-byte specification.
-->
<!ELEMENT stateful_siso (validity, validity)>

<!ELEMENT history (modified+)>
<!ELEMENT modified (#PCDATA)>
<!ATTLIST modified
    version CDATA #REQUIRED
    date CDATA #REQUIRED
>

<!ELEMENT validity (state+)>
<!ELEMENT state EMPTY>
<!ATTLIST state
    type CDATA #REQUIRED
    next CDATA #REQUIRED
    s CDATA #REQUIRED
    e CDATA #IMPLIED
    max CDATA #IMPLIED
>

<!ELEMENT assignments (a*, fub*, fbu*, sub1*, range*)>
<!ATTLIST assignments
    sub NMTOKENS "1A"
    sub1 NMTOKEN #IMPLIED
>

<!ELEMENT a EMPTY>
<!ATTLIST a
    b NMTOKENS #REQUIRED
    u NMTOKENS #REQUIRED
    c CDATA #IMPLIED
    v CDATA #IMPLIED
>

<!ELEMENT fub EMPTY>
<!ATTLIST fub
    b NMTOKENS #REQUIRED
    u NMTOKENS #REQUIRED
    c CDATA #IMPLIED
    ru CDATA #IMPLIED
    rc CDATA #IMPLIED
    v CDATA #IMPLIED
>

<!ELEMENT fbu EMPTY>
<!ATTLIST fbu
    b NMTOKENS #REQUIRED
    u NMTOKENS #REQUIRED
    v CDATA #IMPLIED
>

<!ELEMENT sub1 EMPTY>
<!ATTLIST sub1
    u NMTOKENS #REQUIRED
    c CDATA #IMPLIED
    v CDATA #IMPLIED
>

<!ELEMENT range EMPTY>
<!ATTLIST range
    bFirst NMTOKENS #REQUIRED
    bLast NMTOKENS #REQUIRED
    uFirst NMTOKENS #REQUIRED
    uLast NMTOKENS #REQUIRED
    bMin NMTOKENS #REQUIRED
    bMax NMTOKENS #REQUIRED
    v CDATA #IMPLIED
>

<!-- iso2022 element and sub-elements, lists ISO 2022 announcers and sub-mapping tables -->
<!ELEMENT iso2022 (default2022?, (escape|si|so|ss2|ss3)+)>

<!-- encoding used in the initial state; if this element is missing, then US-ASCII is the initial encoding -->
<!ELEMENT default2022 EMPTY>
<!ATTLIST default2022
    name NMTOKEN #REQUIRED
>

<!--
    sequence attributes contain the hexadecimal byte values of the invocation sequences in a ISO 2022 variant
    name attribute contain canonical names of embedded encodings
    and refer to mapping tables outside of the document that defines an ISO 2022 variant
-->

<!ELEMENT escape EMPTY>
<!ATTLIST escape
    sequence NMTOKENS #REQUIRED
    name NMTOKEN #REQUIRED
>

<!ELEMENT si (designator+)>
<!ELEMENT so (designator+)>
<!ELEMENT ss2 (designator+)>
<!ELEMENT ss3 (designator+)>

<!ELEMENT designator EMPTY>
<!ATTLIST designator
    sequence NMTOKENS #REQUIRED
    name NMTOKEN #REQUIRED
>

=== realitix/Ingres-Community-Edition/src/common/adf/adn/ca-cp874-thai_euro-th-2004.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE characterMapping SYSTEM "charactermapping.dtd">
<!--
** Copyright (c) 2004 Actian Corporation
**
** =============================================================================
** ICU License - ICU 1.8.1 and later
** COPYRIGHT AND PERMISSION NOTICE
** 
** Copyright (c) 1995-2003 International Business Machines Corporation and others
** All rights reserved.
** 
** Permission is hereby granted, free of charge, to any person obtaining a
** copy of this software and associated documentation files (the
** "Software"), to deal in the Software without restriction, including
** without limitation the rights to use, copy, modify, merge, publish,
** distribute, and/or sell copies of the Software, and to permit persons
** to whom the Software is furnished to do so, provided that the above
** copyright notice(s) and this permission notice appear in all copies of
** the Software and that both the above copyright notice(s) and this
** permission notice appear in supporting documentation.
** 
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
** OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
** MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
** OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
** HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL
** INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING
** FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
** NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
** WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
** 
** Except as contained in this notice, the name of a copyright holder
** shall not be used in advertising or otherwise to promote the sale, use
* or other dealings in this Software without prior written authorization
* of the copyright holder.
** =============================================================================
*/
##
## History:
##      25-Jan-2004 (gupsh01)
##          Created from ibm-874_P100-1995. 
##      20-Jun-2005 (gupsh01)
##          Modify this table it is now adapted from windows-874-2000.xml.
##
-->
<characterMapping id="ca-cp8740thai_euro-th-2004" version="2">
 <history>
  <modified version="1" date="25-jan-2004"></modified>
  <modified version="2" date="20-jun-2005"></modified>
 </history>
<validity>
  <state type="FIRST" next="VALID" s="00" e="FF" max="FFFF"/>
 </validity>
 <assignments sub="3F">
  <!-- One to one mappings -->
  <a u="0000" b="00"/>
  <a u="0001" b="01"/>
  <a u="0002" b="02"/>
  <a u="0003" b="03"/>
  <a u="0004" b="04"/>
  <a u="0005" b="05"/>
  <a u="0006" b="06"/>
  <a u="0007" b="07"/>
  <a u="0008" b="08"/>
  <a u="0009" b="09"/>
  <a u="000A" b="0A"/>
  <a u="000B" b="0B"/>
  <a u="000C" b="0C"/>
  <a u="000D" b="0D"/>
  <a u="000E" b="0E"/>
  <a u="000F" b="0F"/>
  <a u="0010" b="10"/>
  <a u="0011" b="11"/>
  <a u="0012" b="12"/>
  <a u="0013" b="13"/>
  <a u="0014" b="14"/>
  <a u="0015" b="15"/>
  <a u="0016" b="16"/>
  <a u="0017" b="17"/>
  <a u="0018" b="18"/>
  <a u="0019" b="19"/>
  <a u="001A" b="1A"/>
  <a u="001B" b="1B"/>
  <a u="001C" b="1C"/>
  <a u="001D" b="1D"/>
  <a u="001E" b="1E"/>
  <a u="001F" b="1F"/>
  <a u="0020" b="20" c=" "/>
  <a u="0021" b="21" c="!"/>
  <a u="0022" b="22" c="&quot;"/>
  <a u="0023" b="23" c="#"/>
  <a u="0024" b="24" c="$"/>
  <a u="0025" b="25" c="%"/>
  <a u="0026" b="26" c="&amp;"/>
  <a u="0027" b="27" c="&apos;"/>
  <a u="0028" b="28" c="("/>
  <a u="0029" b="29" c=")"/>
  <a u="002A" b="2A" c="*"/>
  <a u="002B" b="2B" c="+"/>
  <a u="002C" b="2C" c=","/>
  <a u="002D" b="2D" c="-"/>
  <a u="002E" b="2E" c="."/>
  <a u="002F" b="2F" c="/"/>
  <a u="0030" b="30" c="0"/>
  <a u="0031" b="31" c="1"/>
  <a u="0032" b="32" c="2"/>
  <a u="0033" b="33" c="3"/>
  <a u="0034" b="34" c="4"/>
  <a u="0035" b="35" c="5"/>
  <a u="0036" b="36" c="6"/>
  <a u="0037" b="37" c="7"/>
  <a u="0038" b="38" c="8"/>
  <a u="0039" b="39" c="9"/>
  <a u="003A" b="3A" c=":"/>
  <a u="003B" b="3B" c=";"/>
  <a u="003C" b="3C" c="&lt;"/>
  <a u="003D" b="3D" c="="/>
  <a u="003E" b="3E" c="&gt;"/>
  <a u="003F" b="3F" c="?"/>
  <a u="0040" b="40" c="@"/>
  <a u="0041" b="41" c="A"/>
  <a u="0042" b="42" c="B"/>
  <a u="0043" b="43" c="C"/>
  <a u="0044" b="44" c="D"/>
  <a u="0045" b="45" c="E"/>
  <a u="0046" b="46" c="F"/>
  <a u="0047" b="47" c="G"/>
  <a u="0048" b="48" c="H"/>
  <a u="0049" b="49" c="I"/>
  <a u="004A" b="4A" c="J"/>
  <a u="004B" b="4B" c="K"/>
  <a u="004C" b="4C" c="L"/>
  <a u="004D" b="4D" c="M"/>
  <a u="004E" b="4E" c="N"/>
  <a u="004F" b="4F" c="O"/>
  <a u="0050" b="50" c="P"/>
  <a u="0051" b="51" c="Q"/>
  <a u="0052" b="52" c="R"/>
  <a u="0053" b="53" c="S"/>
  <a u="0054" b="54" c="T"/>
  <a u="0055" b="55" c="U"/>
  <a u="0056" b="56" c="V"/>
  <a u="0057" b="57" c="W"/>
  <a u="0058" b="58" c="X"/>
  <a u="0059" b="59" c="Y"/>
  <a u="005A" b="5A" c="Z"/>
  <a u="005B" b="5B" c="["/>
  <a u="005C" b="5C" c="\"/>
  <a u="005D" b="5D" c="]"/>
  <a u="005E" b="5E" c="^"/>
  <a u="005F" b="5F" c="_"/>
  <a u="0060" b="60" c="`"/>
  <a u="0061" b="61" c="a"/>
  <a u="0062" b="62" c="b"/>
  <a u="0063" b="63" c="c"/>
  <a u="0064" b="64" c="d"/>
  <a u="0065" b="65" c="e"/>
  <a u="0066" b="66" c="f"/>
  <a u="0067" b="67" c="g"/>
  <a u="0068" b="68" c="h"/>
  <a u="0069" b="69" c="i"/>
  <a u="006A" b="6A" c="j"/>
  <a u="006B" b="6B" c="k"/>
  <a u="006C" b="6C" c="l"/>
  <a u="006D" b="6D" c="m"/>
  <a u="006E" b="6E" c="n"/>
  <a u="006F" b="6F" c="o"/>
  <a u="0070" b="70" c="p"/>
  <a u="0071" b="71" c="q"/>
  <a u="0072" b="72" c="r"/>
  <a u="0073" b="73" c="s"/>
  <a u="0074" b="74" c="t"/>
  <a u="0075" b="75" c="u"/>
  <a u="0076" b="76" c="v"/>
  <a u="0077" b="77" c="w"/>
  <a u="0078" b="78" c="x"/>
  <a u="0079" b="79" c="y"/>
  <a u="007A" b="7A" c="z"/>
  <a u="007B" b="7B" c="{"/>
  <a u="007C" b="7C" c="|"/>
  <a u="007D" b="7D" c="}"/>
  <a u="007E" b="7E" c="~"/>
  <a u="007F" b="7F"/>
  <a u="0081" b="81"/>
  <a u="0082" b="82"/>
  <a u="0083" b="83"/>
  <a u="0084" b="84"/>
  <a u="0086" b="86"/>
  <a u="0087" b="87"/>
  <a u="0088" b="88"/>
  <a u="0089" b="89"/>
  <a u="008A" b="8A"/>
  <a u="008B" b="8B"/>
  <a u="008C" b="8C"/>
  <a u="008D" b="8D"/>
  <a u="008E" b="8E"/>
  <a u="008F" b="8F"/>
  <a u="0090" b="90"/>
  <a u="0098" b="98"/>
  <a u="0099" b="99"/>
  <a u="009A" b="9A"/>
  <a u="009B" b="9B"/>
  <a u="009C" b="9C"/>
  <a u="009D" b="9D"/>
  <a u="009E" b="9E"/>
  <a u="009F" b="9F"/>
  <a u="00A0" b="A0" c=" "/>
  <a u="0E01" b="A1" c="ก"/>
  <a u="0E02" b="A2" c="ข"/>
  <a u="0E03" b="A3" c="ฃ"/>
  <a u="0E04" b="A4" c="ค"/>
  <a u="0E05" b="A5" c="ฅ"/>
  <a u="0E06" b="A6" c="ฆ"/>
  <a u="0E07" b="A7" c="ง"/>
  <a u="0E08" b="A8" c="จ"/>
  <a u="0E09" b="A9" c="ฉ"/>
  <a u="0E0A" b="AA" c="ช"/>
  <a u="0E0B" b="AB" c="ซ"/>
  <a u="0E0C" b="AC" c="ฌ"/>
  <a u="0E0D" b="AD" c="ญ"/>
  <a u="0E0E" b="AE" c="ฎ"/>
  <a u="0E0F" b="AF" c="ฏ"/>
  <a u="0E10" b="B0" c="ฐ"/>
  <a u="0E11" b="B1" c="ฑ"/>
  <a u="0E12" b="B2" c="ฒ"/>
  <a u="0E13" b="B3" c="ณ"/>
  <a u="0E14" b="B4" c="ด"/>
  <a u="0E15" b="B5" c="ต"/>
  <a u="0E16" b="B6" c="ถ"/>
  <a u="0E17" b="B7" c="ท"/>
  <a u="0E18" b="B8" c="ธ"/>
  <a u="0E19" b="B9" c="น"/>
  <a u="0E1A" b="BA" c="บ"/>
  <a u="0E1B" b="BB" c="ป"/>
  <a u="0E1C" b="BC" c="ผ"/>
  <a u="0E1D" b="BD" c="ฝ"/>
  <a u="0E1E" b="BE" c="พ"/>
  <a u="0E1F" b="BF" c="ฟ"/>
  <a u="0E20" b="C0" c="ภ"/>
  <a u="0E21" b="C1" c="ม"/>
  <a u="0E22" b="C2" c="ย"/>
  <a u="0E23" b="C3" c="ร"/>
  <a u="0E24" b="C4" c="ฤ"/>
  <a u="0E25" b="C5" c="ล"/>
  <a u="0E26" b="C6" c="ฦ"/>
  <a u="0E27" b="C7" c="ว"/>
  <a u="0E28" b="C8" c="ศ"/>
  <a u="0E29" b="C9" c="ษ"/>
  <a u="0E2A" b="CA" c="ส"/>
  <a u="0E2B" b="CB" c="ห"/>
  <a u="0E2C" b="CC" c="ฬ"/>
  <a u="0E2D" b="CD" c="อ"/>
  <a u="0E2E" b="CE" c="ฮ"/>
  <a u="0E2F" b="CF" c="ฯ"/>
  <a u="0E30" b="D0" c="ะ"/>
  <a u="0E31" b="D1" c="ั"/>
  <a u="0E32" b="D2" c="า"/>
  <a u="0E33" b="D3" c="ำ"/>
  <a u="0E34" b="D4" c="ิ"/>
  <a u="0E35" b="D5" c="ี"/>
  <a u="0E36" b="D6" c="ึ"/>
  <a u="0E37" b="D7" c="ื"/>
  <a u="0E38" b="D8" c="ุ"/>
  <a u="0E39" b="D9" c="ู"/>
  <a u="0E3A" b="DA" c="ฺ"/>
  <a u="0E3F" b="DF" c="฿"/>
  <a u="0E40" b="E0" c="เ"/>
  <a u="0E41" b="E1" c="แ"/>
  <a u="0E42" b="E2" c="โ"/>
  <a u="0E43" b="E3" c="ใ"/>
  <a u="0E44" b="E4" c="ไ"/>
  <a u="0E45" b="E5" c="ๅ"/>
  <a u="0E46" b="E6" c="ๆ"/>
  <a u="0E47" b="E7" c="็"/>
  <a u="0E48" b="E8" c="่"/>
  <a u="0E49" b="E9" c="้"/>
  <a u="0E4A" b="EA" c="๊"/>
  <a u="0E4B" b="EB" c="๋"/>
  <a u="0E4C" b="EC" c="์"/>
  <a u="0E4D" b="ED" c="ํ"/>
  <a u="0E4E" b="EE" c="๎"/>
  <a u="0E4F" b="EF" c="๏"/>
  <a u="0E50" b="F0" c="๐"/>
  <a u="0E51" b="F1" c="๑"/>
  <a u="0E52" b="F2" c="๒"/>
  <a u="0E53" b="F3" c="๓"/>
  <a u="0E54" b="F4" c="๔"/>
  <a u="0E55" b="F5" c="๕"/>
  <a u="0E56" b="F6" c="๖"/>
  <a u="0E57" b="F7" c="๗"/>
  <a u="0E58" b="F8" c="๘"/>
  <a u="0E59" b="F9" c="๙"/>
  <a u="0E5A" b="FA" c="๚"/>
  <a u="0E5B" b="FB" c="๛"/>
  <a u="2013" b="96" c="–"/>
  <a u="2014" b="97" c="—"/>
  <a u="2018" b="91" c="‘"/>
  <a u="2019" b="92" c="’"/>
  <a u="201C" b="93" c="“"/>
  <a u="201D" b="94" c="”"/>
  <a u="2022" b="95" c="•"/>
  <a u="2026" b="85" c="…"/>
  <a u="20AC" b="80" c="€"/>
  <a u="F8C1" b="DB" c=""/>
  <a u="F8C2" b="DC" c=""/>
  <a u="F8C3" b="DD" c=""/>
  <a u="F8C4" b="DE" c=""/>
  <a u="F8C5" b="FC" c=""/>
  <a u="F8C6" b="FD" c=""/>
  <a u="F8C7" b="FE" c=""/>
  <a u="F8C8" b="FF" c=""/>
  <!-- Fallback mappings from Unicode to bytes -->
  <fub u="00A7" b="15" c="§"/>
  <fub u="00B6" b="14" c="¶"/>
  <fub u="203C" b="13" c="‼"/>
  <fub u="2190" b="1B" c="←"/>
  <fub u="2191" b="18" c="↑"/>
  <fub u="2192" b="1A" c="→"/>
  <fub u="2193" b="19" c="↓"/>
  <fub u="2194" b="1D" c="↔"/>
  <fub u="2195" b="12" c="↕"/>
